homepage/urls.py
from django.urls import path
from . import views

app_name='homepage'
urlpatterns = [
    path('', views.Landing,name='Landing'),
    path('books', views.books, name='books_data'),
    path('addLike', views.addLike, name='add_like'),
    path('topBook', views.topBook, name='top_book'),


    # path('likes',views.likes,name='likes')


  
]

story/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('homepage.urls')),
]

homepage/models.py
from django.db import models


class Book(models.Model):
    id = models.CharField(max_length=130, primary_key=True)
    cover = models.CharField(max_length=400)
    title = models.CharField(max_length=200)
    author = models.CharField(max_length=200, blank=True)
    likes = models.IntegerField(default=0)


    def __str__(self):
        return self.title
 

homepage/views.py
from django.shortcuts import render
from django.http import JsonResponse
import json
from .models import Book
import requests
from django.views.decorators.csrf import csrf_exempt

def Landing(request):
	return render(request, 'landing.html')

def books(request):
	q = request.GET['q']
	json_read = requests.get('https://www.googleapis.com/books/v1/volumes?q=' + q)
	b=json_read.json()
	for item in b['items']:
		try:
			book = Book.objects.get(id=item['id'])
			likes = book.likes   
		except:
			likes = 0
		item['volumeInfo']['likes'] = likes 
	return JsonResponse(b)

@csrf_exempt
def addLike(request):
    
    book, created = Book.objects.get_or_create(
        id=request.POST['id'],
        cover=request.POST['cover'],
        title=request.POST['title'],
        author=request.POST['author'],
    )
    book.likes = int(request.POST['likes'])   
    book.save()
    return JsonResponse(book.likes, safe=False)


def topBook(request):

	books= Book.objects.order_by('-likes')[:5]
	library=[]
	for i in books:
		library.append({
			'id' : i.id,
			'cover': i.cover,
			'title': i.title,
			'author':i.author,
			'likes': i.likes
			})
	data={
		'top5' : library
	}
	return JsonResponse(data,safe=False)
	    

homepage/templates/base.html
{% load static %}
<html>
<head>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'style.css' %}">

<style type="text/css">
body {
  background: url('https://static.vecteezy.com/system/resources/previews/000/598/369/non_2x/light-pastel-color-vector-low-poly-crystal-background-polygon-design-pattern-low-poly-illustration-background.jpg') no-repeat center center fixed;
  -webkit-background-size: cover;
  -moz-background-size: cover;
  background-size: cover;
  -o-background-size: cover;
}

</style>
</head>
			{% include 'navbar.html' %}
<body>
    {% block content %}
    {% endblock %}
</body>
</html>

homepage/templates/landing.html
{% load static %}

<html>
<head>
  <title>Faraz's Book Finder</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'style.css' %}">
<style type="text/css">

body {
  background: url('https://media.istockphoto.com/videos/cartoon-library-packed-with-books-in-the-dark-video-id658557636?s=640x640') no-repeat center center fixed;
  -webkit-background-size: cover;
  -moz-background-size: cover;
  background-size: cover;
  -o-background-size: cover;
  height: 100vh;
  color:white;

}
</style>
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

<script>
  const books_data_url = "{% url 'homepage:books_data' %}?q=";
  const add_like_url = "{% url 'homepage:add_like' %}";
  const top_book_url = "{% url 'homepage:top_book' %}";
</script>
</head>
<body> 

  <div class="font1">
   <div class="container pt-3 pl-2">
      <b>Search your favorite book!</b>
  </div>
  <div class="container pt-1 pl-2">
  <h5>“If one cannot enjoy reading a book over and over again, there is no use in reading it at all.”<br>
― Oscar Wilde </h5>
</div>
<div class="container pt-5 pl-2">

    <div class="col-md-3 pt-4">
      <div class="row">
          <input type="text" id="input" placeholder="Search" style="height: 4vh; font-size: 0.3em;width: 10vw" name="test1"></input>
          <button id="submit" class="button1" name="test4" style="font-size: 0.3em">Search</button>


          <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModalCenter" style="margin-top: 2vh" id="modbut" name='mod'>Top 5 Liked books</button>

                                <!-- Modal -->
                                <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true" style="color: black;">
                                  <div class="modal-dialog modal-dialog-centered" role="document">
                                    <div class="modal-content">
                                      <div class="modal-header">
                                        <h5 class="modal-title" id="exampleModalLongTitle">Top 5</h5>
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                          <span aria-hidden="true">&times;</span>
                                        </button>
                                      </div>
                                      <div class="modal-body" style="font-size: 0.2em" id="klasemen">
                                        
                                      </div>
                                      <div class="modal-footer">
                                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                      </div>
                                    </div>
                                  </div>
                                </div>




        </div>
      </div>
    <div class="col-md-12 pt-4">

     <div class="table-responsive" id="Table">
        <table class="table" style="color: white">
            <thead>
                <tr>
                    <th scope="col">Book Title</th>
                    <th scope="col">Cover</th>
                    <th scope="col">Author</th>
                    <th scope="col">Like this book!</th>
                    <th scope="col">Likes</th>                    
                    <th scope="col">ID</th>
                </tr>
            </thead>
            <tbody id="isi">
            
            </tbody>
        </table>
    </div>
  </div>
</div>
  <script src="{% static 'jquery-3.5.0.min.js' %}"></script>
  <script src="{% static 'filejava.js' %}"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>
</div>
</body>
</html>

homepage/templates/navbar.html
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
body {
  font-family: sans-serif;
}

.sidebar {
  height: 100%;
  width: 0;
  position: fixed;
  z-index: 1;
  top: 0;
  left: 0;
  background-color: #111;
  overflow-x: hidden;
  transition: 0.5s;
  padding-top: 60px;
}

.sidebar a {
  padding: 8px 8px 8px 32px;
  text-decoration: none;
  font-size: 25px;
  color: #818181;
  display: block;
  transition: 0.3s;
}

.sidebar a:hover {
  color:#ff6443;
}

.sidebar .closebtn {
  position: absolute;
  top: 0;
  right: 25px;
  font-size: 36px;
  margin-left: 50px;
}

.openbtn {
  font-size: 20px;
  cursor: pointer;
  background-color:#128b86;
  color: white;
  padding: 10px 15px;
  border: none;
}

.openbtn:hover {
  background-color:grey;
}

#main {
  transition: margin-left .5s;
  padding: 16px;
}

/* On smaller screens, where height is less than 450px, change the style of the sidenav (less padding and a smaller font size) */
@media screen and (max-height: 450px) {
  .sidebar {padding-top: 15px;}
  .sidebar a {font-size: 18px;}
}
</style>
</head>
<body>

<div id="mySidebar" class="sidebar">
  <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">×</a>
  <a href="https://story4-trisetio.herokuapp.com">Story4</a>


</div>

<div id="main">
  <button class="openbtn" onclick="openNav()">☰ Open Sidebar</button>  

<script>
function openNav() {
  document.getElementById("mySidebar").style.width = "250px";
  document.getElementById("main").style.marginLeft = "250px";
}

function closeNav() {
  document.getElementById("mySidebar").style.width = "0";
  document.getElementById("main").style.marginLeft= "0";
}
</script>
   
</body>
</html> 